services:
  mysql:
    image: mariadb:11.4
    logging:
      driver: none
    command: ["--max-allowed-packet=512M"]
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - default
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: litespeed
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./sites:/var/www/vhosts/
      - ./acme:/root/.acme.sh/
      - ./logs:/usr/local/lsws/logs/
    ports:
      - 81:81
      - 4433:4433
      - 4433:4433/udp
      - 7080:7080
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.2
    ports:
      - 7070:7070
      - 7474:7474
    environment:
        DATABASE_HOST: mysql
    restart: always
    networks:
      - default
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
  wordpress-installer:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    depends_on:
      - litespeed
      - mysql
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      bash -c "chmod +x ./bin/appinstall.sh && ./bin/appinstall.sh -A wordpress -D localhost"
    restart: "no"
    networks:
      - default
networks:
  default:
    driver: bridge
